version: '3'

services:
  api-gateway:
    build: .
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres-db:5432/mydatabase
      - AUTH_SERVICE=http://app:3000/
      - PORT=5000
    depends_on:
      - postgres-db
    networks:
      - fairplay-api-gateway
      - fairplay

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - fairplay-api-gateway
      - fairplay

networks:
  fairplay-api-gateway:
    driver: bridge
  fairplay:
    external: true
