version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      DATABASE_URL: 'mongodb://mongo:27017/backend-test'
      PORT: 3000
    networks:
      - fairplay-auth-service
      - fairplay

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - fairplay-auth-service
      - fairplay

networks:
  fairplay-auth-service:
    driver: bridge
  fairplay:
    external: true

volumes:
  mongodb_data:
